language: c

before_install:
  - set -e
  - sudo add-apt-repository ppa:team-gcc-arm-embedded/ppa -y
  - sudo apt update -qq
  - sudo apt install gcc-arm-embedded

script:
  - make

cache: ccache

notifications:
  email:
    on_success: never